export enum ActionTypes {
  FETCH_DATA_START,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAILURE,
  FETCH_VIDEO_SUCESSS,
  FETCH_VIDEO_START,
  FETCH_VIDEO_FAILURE,
  FETCH_COMMENTS,
  SIGN_UP,
  LOGIN,
  LOG_OUT,
  AUTHENTICATION_FAILURE,
  FETCH_USER,
}

// export enum SideBarActionTypes {
//   TOGGLE_SIDEBAR,
// }
